### ISSUE TITLE
SHAPE support (experimental)?

### ISSUE THREAD

**Issue by bh0085** [dincarnato/draco#14]
I notice that SHAPE support with the -shape option is marked as experimental in the documentation. SHAPE-map can create a pretty wide ranges of sequencing outcomes such as mutations, insertions and deletions. I was curious: has DRACO's performance with SHAPE data been evaluated?

**Comment by dincarnato** [comment]
Hello,

there are caveats and the data need to be adjusted properly before being fed into DRACO, because, as you said, there are many ambiguous deletions and insertions that are hard to interpret.
We and some other collaborators have ran some pilot experiments and is seems that, with the appropriate reagents (i.e., 2A3) and mutation filtering, DRACO can perform very well with that data.

We might publish this at some point.

Best,
Danny

**Comment by bh0085** [comment]
Thanks for the fast response! I'll look forward to your publication... and trying it out myself on our data.

**Comment by dincarnato** [comment]
You might wanna try the following parameters in `rf-count` when generating your MM files:

`-dc 3 -na -ni -md 1`

Best,
Danny
